workers: 4
batch_size: 192
saved_model: /nfs_shared/STR_Data/graduate_project/SceneTextRecognition/weights/TPS-ResNet-BiLSTM-Attn-Large/best_accuracy.pth
batch_max_length: 25
imgH: 32
imgW: 100
rgb: False
character: /nfs_shared/STR_Data/graduate_project/SceneTextRecognition/character/kr_charset_with_special_utf.txt
sensitive: True
PAD: False
Transformation: TPS
FeatureExtraction: ResNet
SequenceModeling: BiLSTM
Prediction: Attn
num_fiducial: 20
input_channel: 1
output_channel: 512
hidden_size: 256